### PR TITLE
Block not necessary esp's

### PR DESCRIPTION
**Pull request by Asprorpsa**

### CODE REVIEW

**Comment by Asprorpsa** [comment]
When will we update 2.2 to 2.3 on nexus?

It remains to check everything and cancel some exceptions

**Comment by Raulfin** [comment]
Was thinking about putting it up tonight.

**Comment by Asprorpsa** [comment]
Enhanced Blood Main necessarily
http://i68.fastpic.ru/big/2015/0214/0a/07c6d4f4d7bce538b5efee599ef0a00a.jpg

**Comment by Asprorpsa** [comment]
Can I get your updated WAFR, CCOR and CCF patches? :)

**Comment by Raulfin** [comment]
2sec

**Comment by Raulfin** [comment]
https://www.dropbox.com/s/j6mlsaci4wv2vsa/WAFR%20CCOR%20CCF.rar?dl=0

**Comment by Raulfin** [comment]
Pretty sure I got all the stuff from the pack you sent me.

**Comment by Asprorpsa** [comment]
Thx, check it now :)

**Comment by Asprorpsa** [comment]
Done
2 patches updated and 1 new patch
http://filebeam.com/ea03d4ac26b0ad0e5944e10b9c7e1a74

**Comment by Asprorpsa** [comment]
Can you merge my blocklist changes? :) all checked in TESVEDIT and looks fine

**Comment by Raulfin** [comment]
:)

**Pull request merged**
