### PR TITLE
Cleanup and changes

### PR DESCRIPTION
**Pull request by Asprorpsa**
DOWNLOAD LINK'S
http://filebeam.com/e160ee47805e9375c27fb4a64c60ce35 CCF
http://filebeam.com/de5fd41a173242e4bdffa9828e42df71 WAFR (NEW, WITH MISSING KEYWORDS)
http://filebeam.com/f938c462e36b2f833eeec11ab07d2f57 CCOR (WITH RENAMED CIRCLE)
http://filebeam.com/ce092a59f7885787be4d4d529b249530 SIC (MISSED MODEL)

### CODE REVIEW

**Comment by Asprorpsa** [comment]
Done :)

**Comment by Asprorpsa** [comment]
Light Ancient Nord not necessary, we have Ancient Nord Light :)

Guard have identical models, but not have new textures, therefore look like the same
http://i67.fastpic.ru/big/2015/0226/af/43a147c84e0f442d6bd915da1534adaf.jpg
http://i68.fastpic.ru/big/2015/0226/a3/e449dcfe3360960e2cf712b94cddf0a3.jpg
etc.

**Comment by Asprorpsa** [comment]
It's notepad++ encoding corrects
I returned everything as it was

**Comment by Asprorpsa** [comment]
but Imperial Studded doesn't :(

What do you mean? :)

**Comment by Raulfin** [comment]
When you made the masquerade changes to Imperial, Imperial Studded Armor is no longer covered (unless I missed it).

**Comment by Raulfin** [comment]
just saw it :) I had missed it :)

**Comment by Asprorpsa** [comment]
See final changes in "Files changed 5" :)
Already added :)))

**Comment by Raulfin** [comment]
I'll start looking at the esps and getting that done.

**Comment by Asprorpsa** [comment]
kk :)
have a question - Ulfric's Gag is not playable circlet, may be revert this commit https://github.com/Asprorpsa/PCaPP/commit/4c45ac9f6348725073a0ba5a3b6e37833016a0e0 ?
or let it remain as it is? :)

**Comment by Raulfin** [comment]
No need to revert it, it will help make sure the item isn't needlessly patched.

**Comment by Raulfin** [comment]
The Cultist Robe changes in WAFR_FIX are covered by CCF already.

**Comment by Asprorpsa** [comment]
I know
This is for the single WAFR and CCF patches
In merged WAFR\CCF patch CCF will have priority :)

**Comment by Raulfin** [comment]
do you use WAFR 5.0 or 5.1?

**Comment by Asprorpsa** [comment]
I don't have 5.1 :( use 5.0
Where can I get new version? :)

**Comment by Raulfin** [comment]
She put a beta copy on STEP.

**Comment by Raulfin** [comment]
Falmer Heavy Circlet > Falmer Circlet
The keywords and type flag mark it as heavy, changing the name will have PaMa mark it as Light and it will count as both but show as heavy and have AR of Light.

**Comment by Asprorpsa** [comment]
Ok, then... need to rewrite Falmer Heavy to Falmer Heavy Boots, Armor, Gauntlets, Helm and not rename circlet :) 1 second

**Comment by Raulfin** [comment]
'Falmer' and 'Ancient Falmer' are Light
'Hardened Falmer', 'Falmer Hardened' and 'Falmer Heavy' are Heavy

**Comment by Raulfin** [comment]
Falmer Heavy has same AR as Ebony.
Falmer Hardened has same AR as Dwarven.

**Comment by Asprorpsa** [comment]
See this https://github.com/Raulfin/PCaPP/pull/251
I know... just confused, sry :)

**Comment by Raulfin** [comment]
no prob :)

**Comment by Asprorpsa** [comment]
Can I get a new SIC patch now? :P

**Pull request merged**
