### PR TITLE
Ragged correct (can be other values) :)

### PR DESCRIPTION
**Pull request by Asprorpsa**
http://elderscrolls.wikia.com/wiki/Ragged_Robes and etc.?

### CODE REVIEW

**Comment by Asprorpsa** [comment]
how to add some items to exclusions?

**Comment by Raulfin** [comment]
Can't exclude items from modifiers. only way would be to change the item name.

**Comment by Asprorpsa** [comment]
Ok, thx :)
Well, wait a few minutes, modified and test ragged

**Comment by Raulfin** [comment]
Modifiers can also stack, an item named "Broken Thick Officer's Shield" would have all three modifiers (Broken, Thick and Officer) applied in the order they appear in the name, and the same modifier can be applied multiple times "Ragged Ragged Robe" but they are all case-sensitive so a "ragged robe" wouldn't be affected.

**Comment by Asprorpsa** [comment]
Well, see it, don't work and don't need
What do you think about this error? All scrolls bugged

http://fastpic.ru/view/66/2015/0213/bc36931656caecc17dcb2240f22e8f80.jpg.html

NULL have "Rusted Blade" duration and is similar to all the others - wrong calculation

http://fastpic.ru/view/60/2015/0213/12b3dc677c6bac0a973be2550d6985e7.jpg.html
http://fastpic.ru/view/66/2015/0213/0b38ca4b4076e22d499018388ae07de3.jpg.html
And etc.
Can we fix it in xml?

**Comment by Raulfin** [comment]
can't fix those in the xml, I'll take a look at the code and let T3nd0 know.

**Comment by Asprorpsa** [comment]
I've already told him, just have to wait if we can not do anything :(

**Pull request closed without merging**
