### PR TITLE
missed? :)

### PR DESCRIPTION
**Pull request by Asprorpsa**

### CODE REVIEW

**Comment by Asprorpsa** [comment]
Why imperial armor don't patched?
Chitin, stalhrim, bonemold too
All this missed "xMAArmorXXXXXXX" and "xMASPEMasqueradeXXXXXXXXXX" keywords
image

or they refer to Template armor (already patched)? then... all is well :)

**Comment by Raulfin** [comment]
Weapons and Armors with TNAM - Template are ignored by the patcher. The proper damage/armor and keywords are added when the game is loaded.

**Comment by Asprorpsa** [comment]
well, thank you, did not know such details :)

**Comment by Raulfin** [comment]
If filled in, only the Name, Value, and Enchanting fields are used; all of the other values will be inherited from the template.

**Comment by Asprorpsa** [comment]
ok, thx :)

**Pull request closed without merging**
