### PR TITLE
Diverse Bows Support

### PR DESCRIPTION
**Pull request by alyzar**
http://www.nexusmods.com/skyrim/mods/59224/?

### CODE REVIEW

**Comment by InsanePlumber** [comment]
This modification includes a lot of mistakes/errors.
http://forums.nexusmods.com/index.php?/topic/2209044-diverse-bows/page-4#entry23398434

**Comment by alyzar** [comment]
Nice post. Thanks

**Comment by Raulfin** [comment]
that's crazy

**Comment by Raulfin** [comment]
#273

**Pull request merged**
