### PR TITLE
Update Weapons.xml

### PR DESCRIPTION
**Pull request by Asprorpsa**
DOWNLOAD LINK
http://filebeam.com/def56cc14c19f862b5c5958733dd26e9 SIC FIX for your new SIC patch :)

### CODE REVIEW

**Comment by Asprorpsa** [comment]
What do you think about missing model?
http://fastpic.ru/view/60/2015/0226/d41a7322636d7b4d5fb193e7c5cc7a28.jpg.html

Enhanced crossbows in sic patch are identical (ITM)

**Comment by Raulfin** [comment]
The crossbows should have a template added by the patch.

**Comment by Raulfin** [comment]
The Nord Helm model should be fine either way.
about to put on a movie for a bit, will check out the download when it's over.

**Comment by Asprorpsa** [comment]
Enhanced crossbows don't have templates, may be you missed it? :)

http://i57.fastpic.ru/big/2015/0226/b6/3f87f3039bbb07f5e29673f603cf0db6.jpg

**Comment by Raulfin** [comment]
they are now

**Comment by Raulfin** [comment]
merged the sic fix, the Daedric Rusty Mace it has is just a test item,it isn't actually used anywhere for the mod.

**Comment by Asprorpsa** [comment]
Falskaar Ceremonial too? :P
As far as I can see they not have "not playable" flags
Maby can only be obtained through the console?)

**Comment by Asprorpsa** [comment]
```
    <armor_material>
        <armorBase>37</armorBase>
        <identifier>Steel Heavy</identifier>
        <type>HEAVY</type>
        <materialMeltdown>STEEL</materialMeltdown>
        <materialTemper>STEEL</materialTemper>
    </armor_material>
```

:)

**Comment by Raulfin** [comment]
Falskaar Ceremonial armors are part of a quest.

**Comment by Asprorpsa** [comment]
we can wear them? :)

**Comment by Raulfin** [comment]
ya I had forgotten about Steel Heavy, I had needed a higher binding for something and SteelHigh was to low so I had to make up something stupid :)

**Comment by Raulfin** [comment]
ya, the Ceremonial stuff can be worn AFAIK.
from what I can piece together without actually doing the quest is the Broken part is found in a cave, then you "magic" it into the Fixed

**Comment by Raulfin** [comment]
they do need distribuition and enchanting exclusions though

**Comment by Asprorpsa** [comment]
now check this)

**Comment by Raulfin** [comment]
?

**Comment by Asprorpsa** [comment]
```
    <exclusion>
        <text>FSSQ</text>
        <target>EDID</target>
        <type>STARTSWITH</type>
    </exclusion>
```

dont work for enchanting exclusions? only reforged?

**Comment by Raulfin** [comment]
correct

**Comment by Asprorpsa** [comment]
http://i60.fastpic.ru/big/2015/0227/91/0fbdf81dc388c3455e5f65c95f47dc91.jpg
http://i60.fastpic.ru/big/2015/0227/12/79fd2493da22cf2afa2920f178ace512.jpg

This armor could appear in level-lists?
As far as I see, after sorting by name, armor not have enchanted variants... hmm

**Comment by Raulfin** [comment]
bad links

**Comment by Asprorpsa** [comment]
updated links now

**Comment by Raulfin** [comment]
There is a small "issue" me and T were looking into today, PaMa has a habit of... randomly deciding not to make enchanted versions of stuff it should, or make duplicate enchanted versions or enchanted items.

**Comment by Asprorpsa** [comment]
ohh
you talked about this with T3nd0?

**Comment by Raulfin** [comment]
came up in one of our "fix this" talks.

Was looking at the xmls and I didn't do the Falskaar stuff very well

**Comment by Asprorpsa** [comment]
All stuff or individual items?

**Comment by Raulfin** [comment]
the overall mod, it's very spotty, the Ceremonial bindings you had are fine

**Comment by Raulfin** [comment]
my head is being a bit slow right now, was trying to fix an old ceramic pot a bit ago and breathed a lot of glue

**Comment by Asprorpsa** [comment]
ahahah, good to breathe fresh air, not glue vapor :D

can I return Damaged Ceremonial armor? works fine

**Comment by Raulfin** [comment]
Ya, I was smart and left the 2m by 2m window next to me closed....

**Comment by Asprorpsa** [comment]
probably... now it will be better go away from this place :)

**Comment by Raulfin** [comment]
Gophers video for PerMa magic testing just went up, I get to watch the whole 2hr thing now

**Comment by Asprorpsa** [comment]
The main thing.... that was not boring? otherwise drag on for many evenings :)

**Comment by Raulfin** [comment]
His are pretty interesting, he looks at the functionality of things, very detail orianted

**Comment by Asprorpsa** [comment]
would gladly have looked, but did not get along with English :P

**Pull request merged**
