### PR TITLE
InsanitySorrow's Zatoichi, Vayan Armor, Belko follower and VanNord Carved Nordic Armor Support.(Various fixes as well.)

### PR DESCRIPTION
**Pull request by slasherjdc**
Bindings for InsanitySorrow's Zatoichi(26619) (I'm unsure if there is support for have a prefix before and after?)
Bindings for Vayan Armor(61616)
Bindings for Belko(62149)'s Default gear.
Bindings for VanNord Carved Nordic Armour(64560)
Leveled List Exclusions for VanNord Carved Nordic Armour,Vayan(female only) and Belko's Gear.(ignore LL Zatoichi was mistype on heading)
Deadric Crescent Fixed(Immersive Weapons has a 2H and 1H(named the same as LWE 2H) so they are basically incompatible)
Aetherium Armor and Weapons Compilation(23530) Fixes(Dwarven Power Battlexe is how it is in the replacement esp....bolt launcher was missing)
Isilmeriel LOTR Weapons Collection Fix(missing dagger and LL Exclusions)

(Wonder how much i can cram into this patch before you merge it :P)

### CODE REVIEW

**Comment by slasherjdc** [comment]
The spaces were present in the names of the original Zatoichi mod incase that is bugging you(copied the names out of TES5Edit directly like normal).

**Comment by Raulfin** [comment]
#374 
#375 
#376
#377

**Comment by Raulfin** [comment]
It would be easy enough for me to rename Deadric Crescent in the Immersive Weapons patch to match LWE so they are compatible

**Comment by slasherjdc** [comment]
It's lore Weapon that is the problem though
IW    > Great Daedric Cresent - Greatsword
IW    > Daedric Cresent - Arming Sword
LWE > Daedric Cresent - Greatsword

**Comment by Raulfin** [comment]
hmm

**Comment by Raulfin** [comment]
Could do something like;
IW > Daedric Cresent - Greatsword
IW > Daedric Short Cresent - Arming Sword
LWE > Daedric Cresent - Greatsword
But that would create a lot of inconsistencies.

**Comment by slasherjdc** [comment]
certainly could.
could probably use better naming though. :P

**Comment by Raulfin** [comment]
http://www.uesp.net/wiki/Morrowind:Daedric_Crescent

It's a 2 hander naturally, will need to change it in IW.

**Comment by slasherjdc** [comment]
Making more work for you. :/

**Comment by Raulfin** [comment]
"Short Dwarven  Zatoichi" and "Short Ebony  Zatoichi" have an extra space, is that intended?

**Comment by slasherjdc** [comment]
"The spaces were present in the names of the original Zatoichi mod incase that is bugging you(copied the names out of TES5Edit directly like normal)." Commented after
they are all present in the original mod they are bugging the hell out of me.

**Comment by Raulfin** [comment]
kk just making sure, missed the first comment where you said that :)

**Comment by slasherjdc** [comment]
sigh was gonna post it directly but github doesn't allow double space

**Comment by Raulfin** [comment]
the git comment auto-removes double spaces

**Comment by Raulfin** [comment]
What did you mean with this?
"I'm unsure if there is support for have a prefix before and after?"

**Comment by slasherjdc** [comment]
adding 6 lines seemed clunky.
was hoping there was some support for something like "Short %name% Zatoichi"(just an example.)

**Comment by Raulfin** [comment]
ohh, i wish, would save a bit of space with some other bindings also.

**Comment by Raulfin** [comment]
gonna merge it in now, unless you have anything else to add to it first.

**Comment by slasherjdc** [comment]
I think I'm good for now...
running out of mod incompatibilities in my load order :P

**Comment by slasherjdc** [comment]
Aetherium Armor and Weapons Compilation is gonna need a rename for "Dwarven Power Battle(a)xe"

**Comment by Raulfin** [comment]
lol why is it named that...

**Comment by slasherjdc** [comment]
"Dwarven Power Battlexe"
just confirmed its an error from the replacement PCaPP Replacement esp(all the names were changed)
confirmed its not in the original a second ago

**Comment by Raulfin** [comment]
well shit

**Comment by slasherjdc** [comment]
pretty easy to miss was just going through my load order for incompatibilities.

**Comment by Raulfin** [comment]
there are prolly thousands of little things like that all over, the xmls use to be riddled with typo before I put them on git

**Comment by slasherjdc** [comment]
Which is why my fix was to add "Battlexe" to the bindings...gotta be safe.

**Comment by Raulfin** [comment]
I fixed the name for the next patch update.

**Comment by slasherjdc** [comment]
i saw that probably not the only mod that binding fixed though.

**Comment by Raulfin** [comment]
prolly not :)

**Pull request merged**
