### PR TITLE
Sovereign Slayer, True Thief, Morning Star Cleanup

### PR DESCRIPTION
**Pull request by Escavalx**

### CODE REVIEW

**Comment by Raulfin** [comment]
I have no memory of that Ebony Morning Star binding

**Comment by Raulfin** [comment]
@Escavalx 
which True Thief?
True Thief Armor by NewerMind43 http://www.nexusmods.com/skyrim/mods/38409
True Thief Gear by Rodrick1981 http://www.nexusmods.com/skyrim/mods/6464

**Comment by Raulfin** [comment]
#329

**Comment by Escavalx** [comment]
True Thief Armor by NewerMind43 http://www.nexusmods.com/skyrim/mods/38409

**Comment by Raulfin** [comment]
ty :)

#330

**Pull request merged**
