### PR TITLE
A lot of patches

### PR DESCRIPTION
**Pull request by Asprorpsa**
DOWNLOAD LINKS

Fixes to T3nd0 http://filebeam.com/9d8ae0824f90bed1c08d9789bff0c6ae

Fixes to Raulfin http://filebeam.com/3287c59569f34be15958e4eaf262a2b3

### CODE REVIEW

**Comment by Raulfin** [comment]
will take a look at it

**Comment by Raulfin** [comment]
you have changelog for the PerMa stuff?

**Comment by Asprorpsa** [comment]
Yea, inside new archive http://filebeam.com/a87e3cc5bd8edaa398b664f8a1ca7df2

**Comment by Raulfin** [comment]
Vex's AI packages fixes from USKP was left out as it made USKP a master for 1 subrecord.

**Comment by Asprorpsa** [comment]
Update Perkus Maximus Fixes.esp and changelog http://filebeam.com/43766582127f21f86ce7c5656f6808dd :)

New Unofficial Patches merged with CCOR WAFR and CCF + my fixes
http://filebeam.com/66dfd1fc512ba15b752707aed60d53e5

**Pull request closed without merging**
