### PR TITLE
Falmer Heavy

### PR DESCRIPTION
**Pull request by Asprorpsa**

### CODE REVIEW

**Comment by Asprorpsa** [comment]
Done this :)

**Comment by Raulfin** [comment]
lol I've been waiting for xEdit to finish loading for like 10min and I forgot to click load >< :)

**Comment by Asprorpsa** [comment]
:D

**Comment by Raulfin** [comment]
just about done with them

**Comment by Asprorpsa** [comment]
wtf? http://i58.fastpic.ru/big/2015/0226/df/bb7e0fcbdf53f05cbc3a66c9d0bdf9df.jpg
Falmer Circled patched normally :)

only have identical AR with ArmoredCircletFalmer_QuickFox "Falmer Circlet"

Ahh

```
    <binding>
        <identifier>Falmer Hardened</identifier>
        <substring>Falmer Circlet</substring>
    </binding>
```

:)

**Comment by Raulfin** [comment]
found this binding in the xml

```
    <binding>
        <identifier>Falmer Hardened</identifier>
        <substring>Falmer Circlet</substring>
    </binding>
```

**Comment by Raulfin** [comment]
okay, what is the tag for code here? leading and trailing `

**Comment by Raulfin** [comment]
blah, thats dumb have to have a dead line for it to show right

**Comment by Raulfin** [comment]
https://www.dropbox.com/s/h68dbpyk9vvotkp/Pre%20PaMa%20SiC%20Patch.esp?dl=0

**Comment by Asprorpsa** [comment]
He put tag himself
Only need copy and paste :)

Thx!

**Comment by Raulfin** [comment]
I didn't add some of the changes from the fix yet, I'm waiting to hear back from Life about him adding it to SiC.

**Comment by Asprorpsa** [comment]
Ok, then we need re-write changelog? :)

Falmer Shaman Armor (Light) Have Heavy weight, wooooh :D need fix it

**Comment by Raulfin** [comment]
The "Added missed model to Ancient Nord Helmet" the helmet is a non-playable helmet, so it shouldn't be normally visible to the player anyway

**Comment by Asprorpsa** [comment]
Kk

**Comment by Raulfin** [comment]
The other stuff, Falmer shaman, "Correct impact data set and block material on several SIC shields" I did add.

**Comment by Raulfin** [comment]
well to the items that were already covered

**Comment by Raulfin** [comment]
loading it up now, I forget to much stuff

**Comment by Raulfin** [comment]
I'll just add it all in now and edit when he updates SiC.

**Comment by Asprorpsa** [comment]
May be you are interested http://filebeam.com/1298d8df20b39094efee53e0e26811ce
SIC Weapons corrects :)

It's non-patch edits

**Comment by Raulfin** [comment]
kk

**Comment by Asprorpsa** [comment]
there are mistakes made in haste
you can take the changes, if necessary :)

**Comment by Raulfin** [comment]
With the Weapons I think the Non-Playable flag in 'DNAM-Data Flags' covers them not being picked up by the player.
The 'Record Flag' Non-Playable covers (i think) more distribution type stuff.

**Comment by Asprorpsa** [comment]
worse from this, will not (i think) :)

**Comment by Raulfin** [comment]
Take it easy.
I'll prolly update in just a few after I finish this.
Na, I'll get a bit more in and update tomorrow.

**Pull request merged**
