### PR TITLE
Diamond Armor Smithing, SOL,LUNA,TERRA,MARS,VENUS,Yharnyam Set

### PR DESCRIPTION
**Pull request by Escavalx**
#398
#367
#410

Diamond Armor Note
Each piece has a light, heavy, and midweight form. The original midweight Pieces had Light armor bindings that matched the light armor pieces so I used the light armor materials as a baseline for the midweight bindings. I know that having a material as common as diamond/ruby/etc be a standalone binding may be a slight compatability hazard, but doing it this way saves a considerable amount of syntax and nothing stood out as being broken by it so I went for it. If you want me to redo the base bindings as Light (+gem material) and add a new spot for Midweight (+gem Material) let me know in the pull request comments and I will change them up when I see it. I used thick as a midweight binding because it made sense statistically and to a lesser extent conceptually.

Found out that the Black Hands Dagger I had added for Moon and Star was listed already and mine was a duplicate binding, whoops

Luna Note
Refined Versions of Luna didn't seem to be available in the newest version of the mod, so I took them out and gave the 2h versions the Bastard Sword bindings as the author listed the weapons as such. I left the longsword bindings alone as the one handed version does indeed seem to be quite long. The swords with the 1h and 2h suffix were steel, so I bound them as such.

Terra Note
I put the weapon type  bindings together for a little bit more cleanliness

SOL note (decided not to include an issue as full compatability not possible)
Sol Greatsword material binding unnessesary. Has alternate silver versions with the same name as steel version that will not patch properly without an updated esp.

Yharnyam Note
Has an alternate set with the same name, but is clothing, so shouldn't be an issue as far as I know. Both the mask and hat of the Light Armor version are listed as helmets and can be worn together, I have no Idea what side effects come along with that. Armor is distributed via special merchant, so left it reforgeable and added leveledlist and enchantment exclusions.

### CODE REVIEW

**Comment by Raulfin** [comment]
@Escavalx 
I've actually been meaning to attempt to create a Medium armor system. PaMa can already make armor be both light and heavy (Material type BOTH) it just hasn't been used for anything yet. I can only really think of 1-2 items that are even considered medium, so may not be worth it to implement so grand work for it.

**Comment by Raulfin** [comment]
The Refined Silver weapons are made by PaMa, it's like Reforged but makes the item more valuable and not weigh less. Every silver or silverhigh weapon binding needs a matching Rsilver binding.

**Comment by Raulfin** [comment]
That actually showed me a small bug; Silver weapons are getting Reforge/Warforged versions and Reforge/Warforged Refined versions.

**Comment by Escavalx** [comment]
Interesting, I would definitely support a medium armor system, if only to add more options to my characters for their builds. As for armors that would use it, in morrowind bonemeld, Orcish, Stahlrim, and Dragonscale were all medium. Bethesda kind of made changing them back into medium armor difficult by making light and heavy variants of Stahlrim and Dragonscale. Also, the Ebony Mail artifact is actually supposed to be a medium piece and not a normal ebony copy. On a side note, it would be awesome to get an adamantium set w/matching ore, If only so I can bind some of the artifacts better.

**Comment by Escavalx** [comment]
Adding Medium armor would make glass the best light armor again, which is a fairly major power shift for the light armor tree.

**Comment by Escavalx** [comment]
Do silver weapons each need their own binding for the non-refined part, Example: If I were to remove the Luna II binding to silver, would it latch on to the Luna material binding without issue?

**Comment by Raulfin** [comment]
Ya, Luna II should be able to be covered by the Luna material binding.

**Comment by Raulfin** [comment]
The medium system would be a little... weird, I'll add a demo in a bit.

**Pull request merged**
